<div class="clearing">&nbsp;</div>
</div>
</div>
<!-- end wrapper divs -->

<!-- page footer, copyrights, etc. -->
<div id="footer">
<div id="copyrights">
	<small>Copyright | <a href="http://nucleuscms.org"><%version%></a> | 
	<a href="http://validator.w3.org/check?uri=referer">Valid XHTML 1.0 Strict</a> | 
	<a href="http://jigsaw.w3.org/css-validator/">Valid CSS</a> | 
	<a href="#top">Back to top</a></small>
</div>
</div>

</body>
</html>
